# Generated by Django 3.1.5 on 2021-02-03 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import memes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to=memes.models.photos_upload, verbose_name='Upload Photo')),
                ('videos', models.FileField(upload_to=memes.models.videos_upload, verbose_name='Upload Video')),
                ('caption', models.CharField(blank=True, max_length=500, null=True, verbose_name='Enter Caption')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('meme_text', models.TextField(verbose_name='Enter Meme')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
